// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOf1cSPtdC3XAVIgatCPtMC2GJqJFZxYg',
    appId: '1:56236883198:web:880aaeee0fcf911c26f9af',
    messagingSenderId: '56236883198',
    projectId: 'project-neighboard',
    authDomain: 'project-neighboard.firebaseapp.com',
    storageBucket: 'project-neighboard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_cHmLxCj1CX17wsVH-ZiHXiFm1Emv_a0',
    appId: '1:56236883198:android:e2a91f1961da818526f9af',
    messagingSenderId: '56236883198',
    projectId: 'project-neighboard',
    storageBucket: 'project-neighboard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfFkq4hg5f3LKBzvRj8sTHe4n0mcp84FI',
    appId: '1:56236883198:ios:eaf7768cabc80c3b26f9af',
    messagingSenderId: '56236883198',
    projectId: 'project-neighboard',
    storageBucket: 'project-neighboard.appspot.com',
    iosClientId: '56236883198-i0n4l86armn7h4m0312ilbutoc5b083s.apps.googleusercontent.com',
    iosBundleId: 'com.example.neighboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfFkq4hg5f3LKBzvRj8sTHe4n0mcp84FI',
    appId: '1:56236883198:ios:68be88023281c1bb26f9af',
    messagingSenderId: '56236883198',
    projectId: 'project-neighboard',
    storageBucket: 'project-neighboard.appspot.com',
    iosClientId: '56236883198-a97tnef1sug8bjdd3igu2jegl893lfa2.apps.googleusercontent.com',
    iosBundleId: 'com.example.neighboard.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOf1cSPtdC3XAVIgatCPtMC2GJqJFZxYg',
    appId: '1:56236883198:web:6d38efad4e62d24f26f9af',
    messagingSenderId: '56236883198',
    projectId: 'project-neighboard',
    authDomain: 'project-neighboard.firebaseapp.com',
    storageBucket: 'project-neighboard.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBOf1cSPtdC3XAVIgatCPtMC2GJqJFZxYg',
    appId: '1:56236883198:web:7a98d1ec693719f226f9af',
    messagingSenderId: '56236883198',
    projectId: 'project-neighboard',
    authDomain: 'project-neighboard.firebaseapp.com',
    storageBucket: 'project-neighboard.appspot.com',
  );
}
